### ISSUE TITLE
Bad reseed strategy

### ISSUE THREAD

**Issue by TomMD** [vincenthz/hs-cprng-aes#4]
The `CRNG` instance incorporates a bad reseed strategy, reseeding the generator by taking the output of the very generator needing reseeded.

**Comment by vincenthz** [comment]
reseed doesn't, but fork (split) does. could that be an issue ?

**Comment by TomMD** [comment]
I had misread the code prior to making this issue report.  I'll admit, I'm a bit frustrated by what appears to be some RT breakage (EntropyPool unsafeness) - it feels like the "Pseudo" part of PRNG is being thrown under the bus.

I'm not so concerned about the split strategy so long as reseed is solid.

**Comment by vincenthz** [comment]
RT ? (not sure what's this acronym in this context)

yes, some part of the "pseudo" is thrown under the bus. I think letting the user care about all the detail of randomness can't be a good idea after all. My reasoning being that:
- reseeding is an annoyance for the user, it's easier to automatically handle it underneath than expose the nitty gritty details. That simplify the interfaces massively in the end.
- the output of one random generator is the same as the output of another one: the user doesn't care of the value of the randomness, but about the property of randomness (i.e. being random).

It's still quite "pseudo" since the rng itself is pure (the next output is given by the actual state), only the next rng could be "impure", and you can also choose to disable the entropy impure reseeding (for test and debug).

**Comment by TomMD** [comment]
RT --> Referential Transparency.

Your `EntropyPool`s do not actually need to break RT - you could keep an infinitely long lazy bytestring as the pool, which is no different than `LBS.readFile "/dev/urandom"`.  This is what my `SystemRandom` does (it wraps said bytestring, each generation results in a new SystemRandom with the remaining infinite LBS while the prior SystemRandom maintains RT as it's LBS has not changed).  Like `EntropyPool` the `SystemRandom` can only be obtained via `IO`.

In general, this is painful design decision.  You have handled it by implicitly requiring all generators to do reseeding under the covers and instantiating those generators either via a pre-exisitng `EntropyPool` or an `IO` action that can get said pool.  I have handled the situation by admitting these generators have a finite life (returning `Either`) but providing a way to lift that to an exception (`throwLeft`) and a way to reseed under the covers if desired (ex: `GenAutoReseed SystemRandom CtrDRBG`).

It's very much at the crux of our prior API disagreement.  None of this text is ment as a "bug report" at this point - it's just a bit of reflection.

**Comment by vincenthz** [comment]
ah, of course RT=referencial transparency. it kept resolving at Real Time in my brain (and thus make no sense)

I agree with you that your crypto-api's random api has a better design in term of haskellness and purity, pragmatically I think it's either difficult to use or expose stuff that doesn't make sense for the user.

For the entropy pool, it's not a lazy bytestring for security reason. The guarantee provided is that randomness is splattered by new randomness and also the memory is cleaned after use (securemem), provided limited access to previous generated entropy by a resourceful attacker. I agree otherwise that it's not very far in spirit to what you did.

While we arrived pretty much (roughly) at the same solution with the auto re-seeder with the system random, i.e. a non failing API that automatically take care of reseeding, in your case you still have an unnecessary Either type exposed. The difference in the crypto-random case, the API doesn't allow to be used without an automatic re-seeder.

**Comment by TomMD** [comment]
> For the entropy pool, it's not a lazy bytestring for security reason.

Notice the use of LBS is really just convenience.  We could have an infinitely long lazy list of bytes allocated via `allocateScrubedForeignPtr` just as easily.  As a result we would retain RT and scrub the entropy after GC.

I'm strongly considering moving `SystemRandom` to the above solution.

Also, what do you think about proposing a ByteString patch that include scrubbing?  There's no reason we can't have functions such as:

```
mallocScrubbedForeignPtr :: Storable a => IO (ForeignPtr a)
mallocScrubbedForeignPtrBytes :: Int -> IO (ForeignPtr a)
mallocScrubbedByteString :: Int -> IO (GHC.ForeignPtr.ForeignPtr a)
```

which is the core of what `SecureMem` + `Byteable` does via external packages.

**Comment by vincenthz** [comment]
it's slightly reducing what securemem and byteable do.

securemem provides const-EQ, non-showable, scrubbed memory. a future version is quite likely to contains a hand made memory allocator with mlock. There's just no way that bytestring will have those feature.

Byteable is a way to provide cheap conversion operation for everything in the form of:

```
newtype T = T ByteString
```
